Allow Ghost Docker build args.

diff --git a/docker/build/ghost/Dockerfile b/docker/build/ghost/Dockerfile
--- a/docker/build/ghost/Dockerfile
+++ b/docker/build/ghost/Dockerfile
@@ -9,28 +9,48 @@ RUN apk add --no-cache \
 # add "bash" for "[["
 		bash
 
-ENV NODE_ENV production
+# Allow customizing build via build args.
+ARG NODE_ENV=production
+ARG GHOST_CLI_VERSION=1.11.0
+ARG GHOST_INSTALL=/var/lib/ghost
+ARG GHOST_CONTENT=/var/lib/ghost/content
+ARG GHOST_VERSION=2.23.2
 
-ENV GHOST_CLI_VERSION 1.11.0
-RUN npm install -g "ghost-cli@$GHOST_CLI_VERSION"
 
-ENV GHOST_INSTALL /var/lib/ghost
-ENV GHOST_CONTENT /var/lib/ghost/content
+ENV NODE_ENV "${NODE_ENV}"
+ENV GHOST_CLI_VERSION "${GHOST_CLI_VERSION}"
+RUN npm install -g "ghost-cli@${GHOST_CLI_VERSION}"
 
-ENV GHOST_VERSION 2.23.2
+ENV GHOST_INSTALL "${GHOST_INSTALL}"
+ENV GHOST_CONTENT "${GHOST_CONTENT}"
+ENV GHOST_VERSION "${GHOST_VERSION}"
+
+RUN set -x; \
+	echo NODE_ENV "${NODE_ENV}" \
+	GHOST_CLI_VERSION "${GHOST_CLI_VERSION}" \
+	GHOST_INSTALL "${GHOST_INSTALL}" \
+	GHOST_CONTENT "${GHOST_CONTENT}" \
+	GHOST_VERSION "${GHOST_VERSION}";
 
 # ENV BUILD_DEPS \
 # 			python \
 # 			build-base
 
+# Install Ghost.
 RUN set -ex; \
-	mkdir -p "$GHOST_INSTALL"; \
-	chown node:node "$GHOST_INSTALL"; \
+  mkdir -p "${GHOST_INSTALL}"; \
+  chown node:node "${GHOST_INSTALL}"; \
+  su-exec node ghost install "${GHOST_VERSION}" --db sqlite3 --no-prompt --no-stack --no-setup --dir "${GHOST_INSTALL}";
+
+COPY ./build/ghost/config.development.json "${GHOST_INSTALL}/config.development.json"
+
+RUN set -ex; \
 	\
-	su-exec node ghost install "$GHOST_VERSION" --db sqlite3 --no-prompt --no-stack --no-setup --dir "$GHOST_INSTALL"; \
+	chown node:node -R "${GHOST_INSTALL}"; \
+	# su-exec node ghost install "$GHOST_VERSION" --db sqlite3 --no-prompt --no-stack --no-setup --dir "$GHOST_INSTALL"; \
 	\
 # Tell Ghost to listen on all ips and not prompt for additional configuration
-	cd "$GHOST_INSTALL"; \
+	cd "${GHOST_INSTALL}"; \
 	su-exec node ghost config --ip 0.0.0.0 --port 2368 --no-prompt --db sqlite3 --url http://localhost:2368 --dbpath "$GHOST_CONTENT/data/ghost.db"; \
 	su-exec node ghost config paths.contentPath "$GHOST_CONTENT"; \
 	\
@@ -47,10 +67,10 @@ RUN set -ex; \
 	# su-exec node ghost config storage.ghost-storage-cloudinary.fetch.secure = true; \
 	\
 # make a config.json symlink for NODE_ENV=development (and sanity check that it's correct)
-	su-exec node ln -s config.production.json "$GHOST_INSTALL/config.development.json" \
-	&& readlink -f "$GHOST_INSTALL/config.development.json" \
+	# su-exec node ln -s config.production.json "$GHOST_INSTALL/config.development.json" \
+	# && readlink -f "$GHOST_INSTALL/config.development.json" \
 # need to save initial content for pre-seeding empty volumes
-	&& mv "$GHOST_CONTENT" "$GHOST_INSTALL/content.orig" \
+	mv "$GHOST_CONTENT" "$GHOST_INSTALL/content.orig" \
 	&& mkdir -p "$GHOST_CONTENT" \
 	&& chown node:node "$GHOST_CONTENT"
 
@@ -61,15 +81,19 @@ RUN set -eux; \
 # see https://github.com/TryGhost/Ghost/pull/7677 for more details
 	cd "$GHOST_INSTALL/current" \
 # scrape the expected version of sqlite3 directly from Ghost itself
-	&& sqlite3Version="$(npm view . optionalDependencies.sqlite3)"; \
+	&& sqlite3Version="$(npm view . optionalDependencies.sqlite3)" \
+	&& apk add --no-cache --virtual .build-deps python make gcc g++ libc-dev; \
 	if ! su-exec node yarn add "sqlite3@$sqlite3Version" --force; then \
 # must be some non-amd64 architecture pre-built binaries aren't published for, so let's install some build deps and do-it-all-over-again
-		apk add --no-cache --virtual .build-deps python make gcc g++ libc-dev \
-		&& su-exec node yarn add "sqlite3@$sqlite3Version" --force --build-from-source \
-		&& npm install --production --loglevel=error --no-save ghost-storage-cloudinary \
-	  && mv node_modules/ghost-storage-cloudinary core/server/adapters/storage \
-		&& apk del --no-network .build-deps; \
-	fi
+		su-exec node yarn add "sqlite3@$sqlite3Version" --force --build-from-source; \
+	fi; \
+	\
+	# Install Cloudinary storage plugin.
+	# npm install --production --loglevel=error --no-save ghost-storage-cloudinary \
+	# && mv node_modules/ghost-storage-cloudinary core/server/adapters/storage; \
+	\
+	# Cleanup.
+	apk del --no-network .build-deps;
 
 WORKDIR $GHOST_INSTALL
 VOLUME $GHOST_CONTENT
